version: "3.8"

services:
  consul_server:
    container_name: consul_server
    image: hashicorp/consul:1.14
    ports:
      - "8500:8500"
      - "8600:8600"
      - "8300:8300"
    command: 'agent -server -bootstrap-expect=1 -ui -bind=0.0.0.0 -client=0.0.0.0'
    networks:
      - micronetwork

networks:
  micronetwork:
    driver: bridge
